-- Dish Passport — Service 1 (Ingestion) schema.
-- Apply: psql "$DP_DATABASE_URL" -f migrations/001_init.sql
-- Later services add their own tables (dish_flavor_factors, cf_*_factors,
-- user_taste_profiles, flavor_svd_model) in later migrations.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    log_count   INTEGER     NOT NULL DEFAULT 0           -- denormalized for cheap cold-start gating
);

CREATE TABLE IF NOT EXISTS dishes (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     TEXT          NOT NULL,
    canonical_description    TEXT          NOT NULL,      -- cuisine-blind; the dedup key
    ingredients              TEXT[]        NOT NULL DEFAULT '{}',
    prep_method              TEXT,
    embedding                vector(1536)  NOT NULL,      -- opaque "find" vector
    embedding_model_version  TEXT          NOT NULL,
    flavor                   vector(10)    NOT NULL,      -- readable "explain" vector, 0..1 dims
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- HNSW over cosine: the dedup nearest-neighbor probe and (later) retrieval.
CREATE INDEX IF NOT EXISTS dishes_embedding_hnsw
    ON dishes USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS logs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users(id),
    dish_id          BIGINT      NOT NULL REFERENCES dishes(id),
    logged_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    sentiment        TEXT        NOT NULL DEFAULT 'liked'
                     CHECK (sentiment IN ('liked', 'neutral', 'disliked')),
    rating           INTEGER     CHECK (rating BETWEEN 1 AND 5),
    notes            TEXT,
    flavor_override  vector(10)                          -- user refinement; implicit signal (later)
);
CREATE INDEX IF NOT EXISTS logs_user_id_idx ON logs(user_id);
CREATE INDEX IF NOT EXISTS logs_dish_id_idx ON logs(dish_id);

CREATE TABLE IF NOT EXISTS impressions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id),
    dish_id     BIGINT      NOT NULL REFERENCES dishes(id),
    shown_at    TIMESTAMPTZ NOT NULL,
    context     TEXT        NOT NULL CHECK (context IN ('feed', 'recs', 'similar')),
    converted   BOOLEAN     NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS impressions_user_id_idx ON impressions(user_id);
