-- Dish Passport — Supabase migration 0003: core + rec-engine schema.
-- Ports backend/migrations 001–005 faithfully. Changes vs. the originals:
--   * user references are now uuid -> auth.users(id) on delete cascade (was BIGINT -> users)
--   * dish ids and all non-user keys are unchanged (dishes.id stays BIGINT identity)
--   * logs.photo_url (originally added in 005) is folded into the CREATE TABLE

-- ---------------------------------------------------------------------------
-- Service 1 — ingestion: dishes, logs, impressions
-- ---------------------------------------------------------------------------

create table if not exists public.dishes (
    id                       bigint generated by default as identity primary key,
    name                     text          not null,
    canonical_description    text          not null,      -- cuisine-blind; the dedup key
    ingredients              text[]        not null default '{}',
    prep_method              text,
    embedding                vector(1536)  not null,       -- opaque "find" vector
    embedding_model_version  text          not null,
    flavor                   vector(10)    not null,       -- readable "explain" vector, 0..1 dims
    created_at               timestamptz   not null default now()
);

-- HNSW over cosine: the dedup nearest-neighbor probe and (later) retrieval.
create index if not exists dishes_embedding_hnsw
    on public.dishes using hnsw (embedding vector_cosine_ops);

create table if not exists public.logs (
    id               bigint generated by default as identity primary key,
    user_id          uuid        not null references auth.users(id) on delete cascade,
    dish_id          bigint      not null references public.dishes(id),
    logged_at        timestamptz not null default now(),
    sentiment        text        not null default 'liked'
                     check (sentiment in ('liked', 'neutral', 'disliked')),
    rating           integer     check (rating between 1 and 5),
    notes            text,
    flavor_override  vector(10),                            -- user refinement; implicit signal (later)
    photo_url        text                                   -- presigned-PUT S3 URL (from 005)
);
create index if not exists logs_user_id_idx on public.logs(user_id);
create index if not exists logs_dish_id_idx on public.logs(dish_id);

create table if not exists public.impressions (
    id          bigint generated by default as identity primary key,
    user_id     uuid        not null references auth.users(id) on delete cascade,
    dish_id     bigint      not null references public.dishes(id),
    shown_at    timestamptz not null,
    context     text        not null check (context in ('feed', 'recs', 'similar')),
    converted   boolean     not null default false
);
create index if not exists impressions_user_id_idx on public.impressions(user_id);

-- ---------------------------------------------------------------------------
-- Service 3 — flavor + SVD
-- ---------------------------------------------------------------------------

create table if not exists public.flavor_svd_model (
    version          text        primary key,
    components       jsonb       not null,     -- n_factors x 10 loadings
    singular_values  jsonb       not null,     -- n_factors
    mean             jsonb       not null,     -- 10, the centering mean
    factor_labels    jsonb       not null,     -- n_factors, derived from loadings
    created_at       timestamptz not null default now()
);

create table if not exists public.dish_flavor_factors (
    dish_id            bigint      primary key references public.dishes(id),
    factors            vector(4)   not null,
    svd_model_version  text        not null references public.flavor_svd_model(version),
    updated_at         timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Service 4 — collaborative filtering / ALS
-- CF factors are plain float arrays (not pgvector): read as dot products at
-- inference, never indexed for nearest-neighbor.
-- ---------------------------------------------------------------------------

create table if not exists public.cf_user_factors (
    user_id        uuid                primary key references auth.users(id) on delete cascade,
    factors        double precision[]  not null,
    model_version  text                not null,
    computed_at    timestamptz         not null default now()
);

create table if not exists public.cf_item_factors (
    dish_id        bigint              primary key references public.dishes(id),
    factors        double precision[]  not null,
    model_version  text                not null,
    computed_at    timestamptz         not null default now()
);

-- ---------------------------------------------------------------------------
-- Service 5 — recommendation / taste profiles
-- Batch-computed (rebuild_taste_profiles); read on the recommend request path.
-- ---------------------------------------------------------------------------

create table if not exists public.user_taste_profiles (
    user_id             uuid         primary key references auth.users(id) on delete cascade,
    liked_centroid      vector(1536),                 -- mean embedding of liked/neutral dishes
    disliked_centroid   vector(1536),                 -- disliked + decaying soft-neg impressions
    flavor_factor_pref  vector(4),                    -- mean latent factors over liked dishes
    n_dishes            integer      not null default 0,
    updated_at          timestamptz  not null default now()
);
